apiVersion: apps/v1
kind: Deployment
metadata:
  name: xcache-tester
  labels:
    k8s-app: xcache-tester
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: xcache-tester
  template:
    metadata:
      labels:
        k8s-app: xcache-tester
    spec:
      initContainers:
        - name: take-data-dir-ownership
          image: ivukotic/xcache-tester
          command: ["/bin/sh", "-c"]
          args:
            [
              "cp /etc/grid-certs-ro/usercert.pem /etc/grid-certs; chmod 600 /etc/grid-certs/usercert.pem; cp /etc/grid-certs-ro/userkey.pem /etc/grid-certs; chmod 400 /etc/grid-certs/userkey.pem",
            ]
          volumeMounts:
            - name: grid-certs-rw-copy
              mountPath: /etc/grid-certs/
            - name: grid-secret
              mountPath: /etc/grid-certs-ro/
      containers:
        - name: xcache-tester
          image: ivukotic/xcache-tester
          imagePullPolicy: Always
          command: ["sleep"]
          args: ["infinity"]
          volumeMounts:
            - name: grid-certs-rw-copy
              mountPath: /etc/grid-certs/
            - name: grid-secret
              mountPath: /etc/grid-certs-ro/
            - name: rucio-cfg
              mountPath: /opt/rucio/etc/
      volumes:
        # Mount the usercert, userkey, and passphrase file. These will have the
        # wrong permissions to be used for generating the voms proxy
        - name: grid-secret
          secret:
            secretName: grid-certs-secret
        - name: grid-certs-rw-copy
          emptyDir: {}
        - name: rucio-cfg
          configMap:
            name: rucio-config
