name: tests
on:
  push:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    name: build
    steps:
      - uses: actions/checkout@master
      - name: Build Docker Image
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: ivukotic/xcache-tester:latest
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.AAAS_GITOPS_DEPLOY_TRIGGER }}
          repository: maniaclab/river_apps
          event-type: gitops-uc-ls-xcache-tester-trigger
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
  