name: tests
on:
  push:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    name: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.0

      - name: Docker Build & Push Action
        uses: mr-smithers-excellent/docker-build-push@v6.1
        with:
          image: ivukotic/xcache-tester
          tags: latest, ${{ github.sha }}
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2.1.1
        with:
          token: ${{ secrets.AAAS_GITOPS_DEPLOY_TRIGGER }}
          repository: maniaclab/river_apps
          event-type: gitops-uc-ls-xcache-tester-trigger
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
  