name: tests
on:
  push:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    name: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Docker Build & Push to DockerHub
        uses: mr-smithers-excellent/docker-build-push@v6.5
        with:
          image: ivukotic/xcache-tester
          tags: latest, ${{ github.sha }}
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # - name: Docker Build & Push to Harbor
      #   uses: mr-smithers-excellent/docker-build-push@v6.5
      #   with:
      #     image: atlas/xcache-tester
      #     tags: latest, ${{ github.sha }}
      #     registry: hub.opensciencegrid.org
      #     username: ${{ secrets.HARBOR_USERNAME }}
      #     password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3.0.0
        with:
          token: ${{ secrets.AAAS_GITOPS_DEPLOY_TRIGGER }}
          repository: maniaclab/flux_apps
          event-type: gitops-uc-ls-xcache-tester-trigger
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
  